version: '3'

services:
  rabbitmq1:
    build: ./rabbitcluster/.
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}] -setcookie myCookieSecretXCBSDFASDGASFG
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
    ports:
      - 15772:15672
      - 5772:5672
    networks:
      - rabbitnw
  rabbitmq2:
    build: ./rabbitcluster/.
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}] -setcookie myCookieSecretXCBSDFASDGASFG
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
    ports:
      - 15872:15672
      - 5872:5672
    networks:
      - rabbitnw

networks:
  rabbitnw:
    external: true
